DROP TABLE IF EXISTS ConfigurationDataEntity
DROP TABLE IF EXISTS PolicyEntity
DROP TABLE IF EXISTS PolicyDBDaoEntity
DROP TABLE IF EXISTS ActionBodyEntity
DROP SEQUENCE IF EXISTS seqPolicy
DROP SEQUENCE IF EXISTS seqConfig
DROP SEQUENCE IF EXISTS seqActBody
